name: pod
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.4.0
  go_router: ^15.1.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  connectivity_plus:
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
